### ISSUE TITLE
Default macro generate_schema_name doesn't work

### ISSUE THREAD

**Issue by dichenqiandbt** [microsoft/dbt-fabric#266]
Hi team! Dichen from dbt, I got a customer issue reported and I believe it's a bug in fabric adaptor where default generate_schema_name doesn't work.

To reproduce this, choose any fabric project.

- Don't declare generate_schema_name in your macros. I believe dbt would use the default one. See https://docs.getdbt.com/docs/build/custom-schemas#how-does-dbt-generate-a-models-schema-name for the default.
- Declare custom schema name(using +schema) in dbt_project.yml for your model.
- Run a build, check generated SQL you will notice the schema name only has custom schema name without default schema name. This isn't the default behavior. We expect schema name to be {target.name}_{custom_schema_name}
- [Workaround?] Declare generate_schema_name in your macros, simply copy paste the impl from dbt cloud doc. Then schema name would be {target.name}_{custom_schema_name}.

I don't see this issue in snowflake adaptor.

Thank you!

**Comment by shreveasaurus** [comment]
Thanks for opening this @dichenqiandbt! I started to notice this behavior on Feb 20th while using either the dbt Cloud IDE or Cloud CLI.

**Comment by shreveasaurus** [comment]
Is this due to recent to dbt/include/fabric/macros/materializations/models/table/create_table_as.sql ?

https://github.com/microsoft/dbt-fabric/blob/8f0f0d55de2541d23c31a563de9270b93fd1244a/dbt/include/fabric/macros/materializations/models/table/create_table_as.sql

I think this likely causing the issue because:

- The relation object in dbt typically contains schema information
- The old version first created a temporary view with the correct schema prefix, then selected from it
- The new version directly executes the SQL, bypassing the schema prefix handling that might have been happening in the temporary view creation

Current Code
```
{%- else %}
    {%- set query_label_option = query_label.replace("'", "''") -%}
    {%- set sql_with_quotes = sql.replace("'", "''") -%}
    EXEC('CREATE TABLE {{relation}} AS {{sql_with_quotes}} {{ query_label_option }}');
{% endif %}
```

Possible Fix
```
{%- else %}
    {%- set query_label_option = query_label.replace("'", "''") -%}
    {%- set sql_with_quotes = sql.replace("'", "''") -%}
    
    {# Create fully qualified table name with explicit schema #}
    {%- set table_identifier = relation.identifier -%}
    {%- set schema_name = relation.schema -%}
    {%- set fully_qualified_table = '[' ~ schema_name ~ '].[' ~ table_identifier ~ ']' -%}
    
    EXEC('CREATE TABLE {{fully_qualified_table}} AS {{sql_with_quotes}} {{ query_label_option }}');
{% endif %}
```

**Comment by gseda19** [comment]
Hi, a customer reported they started to experience similar issue on Feb 21st. They have applied the workaround to add the default generate_schema_name in their project. However, please note they are using Synapse adapter. It looks like the issue is not limited to fabric adapter?

**Comment by silex-alexis** [comment]
Hi,
Same issue here:
dbt-core 1.8.9 + dbt-sqlserver 1.8.5 + dbt-fabric 1.8.8 -> all good
dbt-core 1.8.9 + dbt-sqlserver 1.8.5 + dbt-fabric 1.8.9 -> breaks, custom_schema is now ignored

I believe it could come from a custom `generate_schema_name` macro which was inserted for test purposes but changes the default expected behaviour of dbt at https://github.com/microsoft/dbt-fabric/commit/4bd7ea9c3efd4064d78e5929101955380d22f352#diff-2dab2f04a9206a68a00332ab56f9bb388a9a75dd3a2edc6e531c5f802982cb42R32

**Comment by ryan-schofield** [comment]
> Hi, Same issue here: dbt-core 1.8.9 + dbt-sqlserver 1.8.5 + dbt-fabric 1.8.8 -> all good dbt-core 1.8.9 + dbt-sqlserver 1.8.5 + dbt-fabric 1.8.9 -> breaks, custom_schema is now ignored
> 
> I believe it could come from a custom `generate_schema_name` macro which was inserted for test purposes but changes the default expected behaviour of dbt at https://github.com/microsoft/dbt-fabric/blob/v1.8.9/dbt/include/fabric/macros/materializations/tests/helpers.sql#L32

This is definitely the issue. The macro defined here is overriding the default, which changes the custom schema naming to: 

  `{{ custom_schema_name | trim }}` 

when it should be: 

  `{{ default_schema }}_{{ custom_schema_name | trim }}`

For now I've corrected this with a custom macro in my project.

**Comment by prdpsvs** [comment]
As an adapter, dbt-fabric should not mess with generate_schema_name macro. I removed the macro in dbt-fabric v1.9.3.
I initially added to handle custom schemas for some test scenarios but with nested cte, it is not required anymore

**Comment by prdpsvs** [comment]
Addressed in 19.3 adapter

**Comment by RobMcZag** [comment]
Hi @prdpsvs I have come here as right now the old, broken, behavior is still present in dbt Cloud using the Latest version when picking a Fabric connection.

Do you know when the Latest version of dbt Cloud will incorporate the latest version with the fix?
